import domain.Person;
import domain.PredicateAndCompareInterface;
import generator.PeopleListGenerator;
import java.util.List;
import static domain.PredicateAndCompareInterface.*;

/**
 * Perform operations filtering and sorting the list generated by PeopleListGenerator.
 */
public class FilterAndSorter {
    static final List<Person> PEOPLE = PeopleListGenerator.generate();

    public static void main(String[] args) {
        usePredicateAndComparator(ifWomanSortByFirstName);
        usePredicateAndComparator(ifBlueEyesSortByLastName);
        usePredicateAndComparator(ifAdultSortByAgeThenLastName);
    }

    /**
     * Uses filterAndSort method to perform filtering and sorting, then printing the elements into console.
     * @param predAndCompI interface with lambda implementation of method filterAndSort
     */
    private static void usePredicateAndComparator(PredicateAndCompareInterface predAndCompI) {
        predAndCompI.filterAndSort(PEOPLE)
                .forEach(System.out::println);
        System.out.println("_______________________________");
    }
}
